import type { Dados } from "./types";

/** ponytail: troque pela cidade real da organização — só aparece em texto. */
export const CIDADE = "Sorocaba";

export const CONTATO = {
  email: "contato@passosverdes.com.br",
  telefone: "+55 15 99999-0000",
  instagram: "@passosverdes",
};

/**
 * Estado inicial da aplicação. Sem backend por enquanto: o admin grava por cima
 * disso no localStorage (ver `lib/store.ts`).
 */
export const SEED: Dados = {
  banners: [
    {
      id: "b1",
      eyebrow: "Temporada 2026 · 4 provas",
      titulo: "A cidade corre",
      destaque: "no escuro",
      subtitulo:
        "Corridas noturnas, provas kids e percursos que atravessam os parques de " +
        CIDADE +
        ". Escolha a sua distância.",
      ctaLabel: "Ver calendário",
      ctaHref: "/eventos",
      imagem: "",
      ativo: true,
    },
    {
      id: "b2",
      eyebrow: "Inscrições abertas",
      titulo: "Passos Verdes",
      destaque: "Kids",
      subtitulo:
        "Percursos de 200 m a 1 km para crianças de 4 a 12 anos, com medalha para todo mundo que cruzar a linha.",
      ctaLabel: "Inscrever a criançada",
      ctaHref: "/eventos",
      imagem: "",
      ativo: true,
    },
  ],
  eventos: [
    {
      id: "e1",
      slug: "noturna-parque-2026",
      nome: "Noturna do Parque",
      edicao: 4,
      modalidade: "noturna",
      data: "2026-09-12",
      horario: "19h30",
      local: "Parque das Águas",
      cidade: CIDADE,
      distancias: ["5 km", "10 km"],
      preco: 89,
      vagas: 1200,
      imagem: "",
      descricao:
        "A prova que fechou o calendário do ano passado abre a temporada em 2026. Largada no anel do parque, percurso todo iluminado por balizadores verdes e chegada com a arquibancada cheia.",
      publicado: true,
    },
    {
      id: "e2",
      slug: "kids-primavera-2026",
      nome: "Kids Primavera",
      edicao: 2,
      modalidade: "kids",
      data: "2026-09-27",
      horario: "09h00",
      local: "Praça Central",
      cidade: CIDADE,
      distancias: ["200 m", "500 m", "1 km"],
      preco: 35,
      vagas: 400,
      imagem: "",
      descricao:
        "Baterias por faixa etária, dos 4 aos 12 anos. Cada criança escolhe a distância e leva medalha ao cruzar a linha. Acompanhante de um responsável liberado no percurso de 200 m.",
      publicado: true,
    },
    {
      id: "e3",
      slug: "circuito-verde-10k",
      nome: "Circuito Verde",
      edicao: 7,
      modalidade: "rua",
      data: "2026-11-08",
      horario: "06h30",
      local: "Avenida Beira-Rio",
      cidade: CIDADE,
      distancias: ["5 km", "10 km", "21 km"],
      preco: 120,
      vagas: 2500,
      imagem: "",
      descricao:
        "A prova mais antiga da Passos Verdes, e a única com meia maratona. Percurso plano à beira do rio, cronometragem por chip e pelotão de elite na frente.",
      publicado: true,
    },
    {
      id: "e4",
      slug: "trail-serra-2026",
      nome: "Trail da Serra",
      edicao: 1,
      modalidade: "trail",
      data: "2026-12-06",
      horario: "07h00",
      local: "Serra do Itapeva",
      cidade: CIDADE,
      distancias: ["12 km", "24 km"],
      preco: 150,
      vagas: 600,
      imagem: "",
      descricao:
        "Primeira edição. Trilha técnica, 780 m de ganho de elevação e dois pontos de hidratação. Recomendada para quem já correu 10 km em terreno irregular.",
      publicado: true,
    },
    {
      id: "e5",
      slug: "noturna-parque-2025",
      nome: "Noturna do Parque",
      edicao: 3,
      modalidade: "noturna",
      data: "2025-09-13",
      horario: "19h30",
      local: "Parque das Águas",
      cidade: CIDADE,
      distancias: ["5 km", "10 km"],
      preco: 79,
      vagas: 1000,
      imagem: "",
      descricao: "Edição de 2025, com 968 corredores na linha de chegada.",
      publicado: true,
    },
    {
      id: "e6",
      slug: "circuito-verde-2025",
      nome: "Circuito Verde",
      edicao: 6,
      modalidade: "rua",
      data: "2025-11-09",
      horario: "06h30",
      local: "Avenida Beira-Rio",
      cidade: CIDADE,
      distancias: ["5 km", "10 km", "21 km"],
      preco: 110,
      vagas: 2200,
      imagem: "",
      descricao: "Recorde de público: 2.140 inscritos e 1.987 concluintes.",
      publicado: true,
    },
    {
      id: "e7",
      slug: "kids-verao-2025",
      nome: "Kids Verão",
      edicao: 1,
      modalidade: "kids",
      data: "2025-12-14",
      horario: "08h30",
      local: "Praça Central",
      cidade: CIDADE,
      distancias: ["200 m", "500 m"],
      preco: 30,
      vagas: 300,
      imagem: "",
      descricao: "A primeira prova kids da organização, com 287 crianças.",
      publicado: true,
    },
  ],
  inscricoes: [
    {
      id: "i1",
      eventoId: "e1",
      nome: "Ana Rodrigues",
      email: "ana.rodrigues@exemplo.com",
      telefone: "15 98812-3344",
      nascimento: "1994-03-18",
      sexo: "F",
      distancia: "10 km",
      camiseta: "P",
      equipe: "Clube da Manhã",
      criadaEm: "2026-07-02T13:04:00.000Z",
    },
    {
      id: "i2",
      eventoId: "e1",
      nome: "Bruno Tavares",
      email: "bruno.tavares@exemplo.com",
      telefone: "15 99120-7788",
      nascimento: "1988-11-02",
      sexo: "M",
      distancia: "5 km",
      camiseta: "G",
      equipe: "",
      criadaEm: "2026-07-05T21:47:00.000Z",
    },
    {
      id: "i3",
      eventoId: "e1",
      nome: "Carla Menezes",
      email: "carla.menezes@exemplo.com",
      telefone: "15 99771-2210",
      nascimento: "2001-06-25",
      sexo: "F",
      distancia: "10 km",
      camiseta: "M",
      equipe: "Pace Livre",
      criadaEm: "2026-07-11T09:12:00.000Z",
    },
    {
      id: "i4",
      eventoId: "e2",
      nome: "Davi Prado",
      email: "familia.prado@exemplo.com",
      telefone: "15 98450-1199",
      nascimento: "2017-01-30",
      sexo: "M",
      distancia: "500 m",
      camiseta: "PP",
      equipe: "",
      criadaEm: "2026-07-19T16:20:00.000Z",
    },
    {
      id: "i5",
      eventoId: "e3",
      nome: "Eduarda Lima",
      email: "eduarda.lima@exemplo.com",
      telefone: "15 99333-0102",
      nascimento: "1979-09-09",
      sexo: "F",
      distancia: "21 km",
      camiseta: "M",
      equipe: "Beira-Rio Runners",
      criadaEm: "2026-07-24T11:55:00.000Z",
    },
  ],
};
